create table lodes_rac_block as
 SELECT 
    geo.geoid, 
    geo.geom,
    lodes_rac.bg_h_geoid,
    sum(lodes_rac.lodes_rac__total_number_of_jobs) AS lodes_rac__total_number_of_jobs,
    sum(lodes_rac.lodes_rac__number_of_jobs_29_or_younger) AS lodes_rac__number_of_jobs_29_or_younger,
    sum(lodes_rac.lodes_rac__number_of_jobs_30_to_34) AS lodes_rac__number_of_jobs_30_to_34,
    sum(lodes_rac.lodes_rac__number_of_jobs_55_or_older) AS lodes_rac__number_of_jobs_55_or_older,
    sum(lodes_rac.lodes_rac__number_of_jobs_1250_month_or_less) AS lodes_rac__number_of_jobs_1250_month_or_less,
    sum(lodes_rac.lodes_rac__number_of_jobs_1251_to_3333_month) AS lodes_rac__number_of_jobs_1251_to_3333_month,
    sum(lodes_rac.lodes_rac__number_of_jobs_greater_than_3333_month) AS lodes_rac__number_of_jobs_greater_than_3333_month,
    sum(lodes_rac.lodes_rac__number_of_jobs_agr_forestry_fish_hunt) AS lodes_rac__number_of_jobs_agr_forestry_fish_hunt,
    sum(lodes_rac.lodes_rac__number_of_jobs_mining_quarry_oil_gas) AS lodes_rac__number_of_jobs_mining_quarry_oil_gas,
    sum(lodes_rac.lodes_rac__number_of_jobs_utilities) AS lodes_rac__number_of_jobs_utilities,
    sum(lodes_rac.lodes_rac__number_of_jobs_construction) AS lodes_rac__number_of_jobs_construction,
    sum(lodes_rac.lodes_rac__number_of_jobs_manufacturing) AS lodes_rac__number_of_jobs_manufacturing,
    sum(lodes_rac.lodes_rac__number_of_jobs_wholesale_trade) AS lodes_rac__number_of_jobs_wholesale_trade,
    sum(lodes_rac.lodes_rac__number_of_jobs_retail_trade) AS lodes_rac__number_of_jobs_retail_trade,
    sum(lodes_rac.lodes_rac__number_of_jobs_transport_warehousing) AS lodes_rac__number_of_jobs_transport_warehousing,
    sum(lodes_rac.lodes_rac__number_of_jobs_information) AS lodes_rac__number_of_jobs_information,
    sum(lodes_rac.lodes_rac__number_of_jobs_finance_insurance) AS lodes_rac__number_of_jobs_finance_insurance,
    sum(lodes_rac.lodes_rac__number_of_jobs_real_estate_rental_leasing) AS lodes_rac__number_of_jobs_real_estate_rental_leasing,
    sum(lodes_rac.lodes_rac__number_of_jobs_prof_sci_tech_services) AS lodes_rac__number_of_jobs_prof_sci_tech_services,
    sum(lodes_rac.lodes_rac__number_of_jobs_mgmt) AS lodes_rac__number_of_jobs_mgmt,
    sum(lodes_rac.lodes_rac__number_of_jobs_admin_support_waste_mgmt) AS lodes_rac__number_of_jobs_admin_support_waste_mgmt,
    sum(lodes_rac.lodes_rac__number_of_jobs_edu_services) AS lodes_rac__number_of_jobs_edu_services,
    sum(lodes_rac.lodes_rac__number_of_jobs_health_care_social_assist) AS lodes_rac__number_of_jobs_health_care_social_assist,
    sum(lodes_rac.lodes_rac__number_of_jobs_arts_entertainment_rec) AS lodes_rac__number_of_jobs_arts_entertainment_rec,
    sum(lodes_rac.lodes_rac__number_of_jobs_accomodation_food_srvcs) AS lodes_rac__number_of_jobs_accomodation_food_srvcs,
    sum(lodes_rac.lodes_rac__number_of_jobs_other_services) AS lodes_rac__number_of_jobs_other_services,
    sum(lodes_rac.lodes_rac__number_of_jobs_public_admin) AS lodes_rac__number_of_jobs_public_admin,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_white) AS lodes_rac__number_of_jobs_race_white,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_black) AS lodes_rac__number_of_jobs_race_black,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_american_indian) AS lodes_rac__number_of_jobs_race_american_indian,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_asian) AS lodes_rac__number_of_jobs_race_asian,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_hawaiian_other_pacific) AS lodes_rac__number_of_jobs_race_hawaiian_other_pacific,
    sum(lodes_rac.lodes_rac__number_of_jobs_race_two_or_more_races) AS lodes_rac__number_of_jobs_race_two_or_more_races,
    sum(lodes_rac.lodes_rac__number_of_jobs_not_hispanic) AS lodes_rac__number_of_jobs_not_hispanic,
    sum(lodes_rac.lodes_rac__number_of_jobs_hispanic) AS lodes_rac__number_of_jobs_hispanic,
    sum(lodes_rac.lodes_rac__number_of_jobs_edu_less_than_high_school) AS lodes_rac__number_of_jobs_edu_less_than_high_school,
    sum(lodes_rac.lodes_rac__number_of_jobs_edu_high_school_or_equivalent) AS lodes_rac__number_of_jobs_edu_high_school_or_equivalent,
    sum(lodes_rac.lodes_rac__number_of_jobs_edu_some_college_or_assoc_degree) AS lodes_rac__number_of_jobs_edu_some_college_or_assoc_degree,
    sum(lodes_rac.lodes_rac__number_of_jobs_edu_bachelor_or_advanced_degree) AS lodes_rac__number_of_jobs_edu_bachelor_or_advanced_degree,
    sum(lodes_rac.lodes_rac__number_of_jobs_sex_male) AS lodes_rac__number_of_jobs_sex_male,
    sum(lodes_rac.lodes_rac__number_of_jobs_sex_female) AS lodes_rac__number_of_jobs_sex_female
   FROM lodes_rac
   JOIN geo_block geo ON geo.geoid = lodes_rac.h_geocode
  GROUP BY lodes_rac.bg_h_geoid, geo.geom, geo.geoid

