alter table roanoke_county_mview
rename column household__total__below_poverty_level__count__1 to house__total__below_poverty_level__count__1;

alter table roanoke_county_mview
rename column house__total__median_home_value__usd to houseunit__total__median_home_value__usd;

alter table roanoke_county_mview
drop column houseunit__total__vacant_for_rent__count__1;

alter table roanoke_county_mview
rename column pop__18_and_over__all__count to pop__total__18_and_over__count;


alter table roanoke_county_mview
rename column pop__female__18_and_over__count to pop__18_and_over__female__count;

alter table roanoke_county_mview
drop column pop__total__over_25__count__1; 

alter table roanoke_county_mview
drop column pop__total__over_5__count__1;


----


alter table roanoke_county_mview
drop column pop__commute_time__10_to_14_min__count__1 ;


alter table roanoke_county_mview
drop column pop__commute_time__15_to_19_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__20_to_24_min__count__1;


alter table roanoke_county_mview
drop column pop__commute_time__25_to_29_min__count__1;


alter table roanoke_county_mview
drop column pop__commute_time__30_to_34_min__count__1;


alter table roanoke_county_mview
drop column pop__commute_time__35_to_39_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__40_to_44_min__count__1;


alter table roanoke_county_mview
drop column pop__commute_time__45_to_59_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__5_to_9_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__60_to_89_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__less_than_5_min__count__1;

alter table roanoke_county_mview
drop column pop__commute_time__more_than_90_min__count__1;