sum(hh_frac * household__total__total_households__count as household__total__total_households__count,
sum(hh_frac * household__total__gross_hh_density__count as household__total__gross_hh_density__count,
sum(hh_frac * household__total__block_density__count as household__total__block_density__count,
sum(hh_frac * household__total__employment_access_index__count as household__total__employment_access_index__count,
sum(hh_frac * household__total__local_job_density__count as household__total__local_job_density__count,
sum(hh_frac * household__total__local_retail_job_density__count as household__total__local_retail_job_density__count,
sum(hh_frac * household__total__retail_access_index__count as household__total__retail_access_index__count,

COALESCE(sum(hh_frac * household__total__area_median_income__usd) / NULLIF(sum(hh_frac),0),0) as household__total__area_median_income__usd,
COALESCE(sum(hh_frac * household__total__blkgrp_median_income_owners__usd) / NULLIF(sum(hh_frac),0),0) as household__total__blkgrp_median_income_owners__usd,
COALESCE(sum(hh_frac * household__total__blkgrp_median_income_renters__usd) / NULLIF(sum(hh_frac),0),0) as household__total__blkgrp_median_income_renters__usd,
COALESCE(sum(hh_frac * household__total__avg_hh_size_owners__avg) / NULLIF(sum(hh_frac),0),0) as household__total__avg_hh_size_owners__avg,
COALESCE(sum(hh_frac * household__total__avg_hh_size_renters__avg) / NULLIF(sum(hh_frac),0),0) as household__total__avg_hh_size_renters__avg,
COALESCE(sum(hh_frac * household__total__commuters_per_hh_owners__avg) / NULLIF(sum(hh_frac),0),0) as household__total__commuters_per_hh_owners__avg,
COALESCE(sum(hh_frac * household__total__commuters_per_hh_renters__avg) / NULLIF(sum(hh_frac),0),0) as household__total__commuters_per_hh_renters__avg,
COALESCE(sum(hh_frac * household__total__pct_renters__percent) / NULLIF(sum(hh_frac),0),0) as household__total__pct_renters__percent,
COALESCE(sum(hh_frac * household__total__median_rooms_per_owner_unit__avg) / NULLIF(sum(hh_frac),0),0) as household__total__median_rooms_per_owner_unit__avg,
COALESCE(sum(hh_frac * household__total__median_rooms_per_renter_unit__avg) / NULLIF(sum(hh_frac),0),0) as household__total__median_rooms_per_renter_unit__avg,
COALESCE(sum(hh_frac * household__total__commuters_per_hh_renters__avg) / NULLIF(sum(hh_frac),0),0) as household__total__commuters_per_hh_renters__avg,
COALESCE(sum(hh_frac * household__total__pct_detatched_single_family_unit__percent) / NULLIF(sum(hh_frac),0),0) as household__total__pct_detatched_single_family_unit__percent,
COALESCE(sum(hh_frac * household__total__median_commute_distance__avg) / NULLIF(sum(hh_frac),0),0) as household__total__median_commute_distance__avg,
COALESCE(sum(hh_frac * household__total__median_rooms_per_renter_unit__avg) / NULLIF(sum(hh_frac),0),0) as household__total__median_rooms_per_renter_unit__avg,
COALESCE(sum(hh_frac * household__total__commuters_per_hh_renters__avg) / NULLIF(sum(hh_frac),0),0) as household__total__commuters_per_hh_renters__avg

