-- Materialized View: dashboard_blockgroup_mview

-- DROP MATERIALIZED VIEW dashboard_blockgroup_mview;

CREATE MATERIALIZED VIEW dashboard_blockgroup_mview AS 
 SELECT block_group_geo.shid,
    dp_block_group.geoid AS bg_id,
    dp_block_group.ueee001 AS pop__total__total_pop__count__1,
    dp_block_group.ugse002 + dp_block_group.ugse003 + dp_block_group.ugse004 + dp_block_group.ugse005 + dp_block_group.ugse006 + dp_block_group.ugse007 + dp_block_group.ugse008 + dp_block_group.ugse009 + dp_block_group.ugse010 + dp_block_group.ugse011 + dp_block_group.ugse012 AS pop__education__less_than_9th_grade__count__1,
    dp_block_group.ugse013 + dp_block_group.ugse014 + dp_block_group.ugse015 + dp_block_group.ugse016 AS pop__education__9th_to_12th_no_diploma__count__2,
    dp_block_group.ugse017 + dp_block_group.ugse018 AS pop__education__high_school_degree__count__3,
    dp_block_group.ugse019 + dp_block_group.ugse020 AS pop__education__some_college_no_degree__count__4,
    dp_block_group.ugse021 AS pop__education__associates_degree__count__5,
    dp_block_group.ugse022 AS pop__education__bachelors_degree__count__6,
    dp_block_group.ugse023 + dp_block_group.ugse024 + dp_block_group.ugse025 AS pop__education__graduate_degree__count__7,
    dp_block_group.ueye003 AS pop__race__total_pop_white__count__1,
    dp_block_group.ueye004 AS pop__race__total_pop_black__count__2,
    dp_block_group.ueye005 AS pop__race__total_pop_american_indian__count__3,
    dp_block_group.ueye006 AS pop__race__total_pop_asian__count__4,
    dp_block_group.ueye007 AS pop__race__total_pop_pacific_islander__count__5,
    dp_block_group.ueye008 AS pop__race__total_pop_other__count__6,
    dp_block_group.ueye012 AS pop__race__total_pop_hispanic__count__7,
    dp_block_group.ueee003 + dp_block_group.ueee027 AS pop__age__age_under_5__count__1,
    dp_block_group.ueee004 + dp_block_group.ueee028 AS pop__age__age_5_9__count__2,
    dp_block_group.ueee005 + dp_block_group.ueee029 AS pop__age__age_10_14__count__3,
    dp_block_group.ueee006 + dp_block_group.ueee007 + dp_block_group.ueee030 + dp_block_group.ueee031 AS pop__age__age_15_19__count__4,
    dp_block_group.ueee008 + dp_block_group.ueee009 + dp_block_group.ueee010 + dp_block_group.ueee032 + dp_block_group.ueee033 + dp_block_group.ueee034 AS pop__age__age_20_24__count__5,
    dp_block_group.ueee011 + dp_block_group.ueee012 + dp_block_group.ueee035 + dp_block_group.ueee036 AS pop__age__age_25_34__count__6,
    dp_block_group.ueee013 + dp_block_group.ueee014 + dp_block_group.ueee037 + dp_block_group.ueee038 AS pop__age__age_35_44__count__7,
    dp_block_group.ueee015 + dp_block_group.ueee016 + dp_block_group.ueee039 + dp_block_group.ueee040 AS pop__age__age_45_54__count__8,
    dp_block_group.ueee017 + dp_block_group.ueee041 AS pop__age__age_55_59__count__9,
    dp_block_group.ueee018 + dp_block_group.ueee019 + dp_block_group.ueee042 + dp_block_group.ueee043 AS pop__age__age_60_64__count__10,
    dp_block_group.ueee020 + dp_block_group.ueee021 + dp_block_group.ueee022 + dp_block_group.ueee044 + dp_block_group.ueee045 + dp_block_group.ueee046 AS pop__age__age_65_74__count__11,
    dp_block_group.ueee023 + dp_block_group.ueee024 + dp_block_group.ueee047 + dp_block_group.ueee048 AS pop__age__age_75_84__count__12,
    dp_block_group.ueee025 + dp_block_group.ueee049 AS pop__age__age_over_85__count__13,
    dp_block_group.ueee026 AS pop__gender__total_pop_female__count__1,
    dp_block_group.ueee002 AS pop__gender__total_pop_male__count__2,
    bg3.ulhe001 AS houseunit__total__total_housing_units__count__1,
    bg2.uhce001 AS household__total__total_household__count__1,
    bg3.ukye001 AS houseunit__total__total_vacant_housing_units__count__1,
    bg3.uk2e001 AS houseunit__total__total_occupied_housing_units__count__1,
    COALESCE((1 * bg3.uk2e003 + 2 * bg3.uk2e004 + 3 * bg3.uk2e005 + 4 * bg3.uk2e006 + 5 * bg3.uk2e007 + 6 * bg3.uk2e008 + 7 * bg3.uk2e009 + 1 * bg3.uk2e011 + 2 * bg3.uk2e012 + 3 * bg3.uk2e013 + 4 * bg3.uk2e014 + 5 * bg3.uk2e015 + 6 * bg3.uk2e016 + 7 * bg3.uk2e017)::numeric / NULLIF((bg3.uk2e002 + bg3.uk2e010)::numeric, 0::numeric), 0::numeric) AS household__total__average_family_size__count__1,
    bg2.umme001 AS houseunit__total__median_home_value__usd__1,
    bg2.umke002 + bg2.umke003 + bg2.umke004 + bg2.umke005 + bg2.umke006 + bg2.umke007 + bg2.umke008 + bg2.umke009 AS houseunit__value__50000_or_less__usd__1,
    bg2.umke010 + bg2.umke011 + bg2.umke012 + bg2.umke013 + bg2.umke014 AS houseunit__value__50000_to_99999__usd__2,
    bg2.umke015 + bg2.umke016 AS houseunit__value__100000_to_149999__usd__3,
    bg2.umke017 + bg2.umke018 AS houseunit__value__150000_to_199999__usd__4,
    bg2.umke019 + bg2.umke020 AS houseunit__value__200000_to_299999__usd__5,
    bg2.umke021 + bg2.umke022 AS houseunit__value__300000_to_499999__usd__6,
    bg2.umke023 + bg2.umke024 AS houseunit__value__500000_to_999999__usd__7,
    bg2.umke025 AS houseunit__value__1000000_or_more__usd__8,
    bg2.ul9e001 AS houseunit__total__median_home_rent__usd__1,
    bg2.ul8e003 + bg2.ul8e004 + bg2.ul8e005 AS houseunit__rent__200_or_less__usd__1,
    bg2.ul8e006 + bg2.ul8e007 AS houseunit__rent__200_to_299__usd__2,
    bg2.ul8e008 + bg2.ul8e009 + bg2.ul8e010 + bg2.ul8e011 AS houseunit__rent__300_to_499__usd__3,
    bg2.ul8e012 + bg2.ul8e013 + bg2.ul8e014 + bg2.ul8e015 + bg2.ul8e016 AS houseunit__rent__500_to_749__usd__4,
    bg2.ul8e017 + bg2.ul8e018 + bg2.ul8e019 AS houseunit__rent__750_to_999__usd__5,
    bg2.ul8e020 + bg2.ul8e021 AS houseunit__rent__1000_to_1499__usd__6,
    bg2.ul8e022 + bg2.ul8e023 AS houseunit__rent__1500_or_more__usd__7,
    bg2.uj8e002 AS pop__labor_force__in_labor_force__count__1,
    bg2.uj8e007 AS pop__labor_force__not_in_labor_force__count__2,
    bg2.uj8e003 AS pop__military_labor__civilian__count__3,
    bg2.uj8e006 AS pop__military_labor__military__count__4,
    bg2.uj8e004 AS pop__civilian_employment__employed__count__5,
    bg2.uj8e005 AS pop__civilian_employment__unemployed__count__6,
    bg2.ukke003 + bg2.ukke030 AS pop__industry__agriculture_fishing_mining__count__1,
    bg2.ukke006 + bg2.ukke033 AS pop__industry__construction__count__2,
    bg2.ukke007 + bg2.ukke034 AS pop__industry__manufacturing__count__3,
    bg2.ukke008 + bg2.ukke035 AS pop__industry__wholesale_trade__count__4,
    bg2.ukke009 + bg2.ukke036 AS pop__industry__retail_trade__count__5,
    bg2.ukke010 + bg2.ukke037 AS pop__industry__transportation__count__6,
    bg2.ukke013 + bg2.ukke040 AS pop__industry__information__count__7,
    bg2.ukke014 + bg2.ukke041 AS pop__industry__finance_and_insurance__count__8,
    bg2.ukke017 + bg2.ukke044 AS pop__industry__scientific_and_professional__count__9,
    bg2.ukke021 + bg2.ukke048 AS pop__industry__education_and_health_care__count__10,
    bg2.ukke024 + bg2.ukke051 AS pop__industry__arts_food_and_entertainment__count__11,
    bg2.ukke028 + bg2.ukke055 AS pop__industry__public_administration__count__12,
    bg2.ukke027 + bg2.ukke054 AS pop__industry__other_services__count__13,
    bg2.uhde001 AS household__total__median_household_income__usd__1,
    bg2.uhce002 AS household__income__10000_or_less__usd__1,
    bg2.uhce003 AS household__income__10000_to_14999__usd__2,
    bg2.uhce004 + bg2.uhce005 AS household__income__15000_to_24999__usd__3,
    bg2.uhce006 + bg2.uhce007 AS household__income__25000_to_34999__usd__4,
    bg2.uhce008 + bg2.uhce009 + bg2.uhce010 AS household__income__35000_to_49999__usd__5,
    bg2.uhce011 + bg2.uhce012 AS household__income__50000_to_74999__usd__6,
    bg2.uhce013 AS household__income__75000_to_99999__usd__7,
    bg2.uhce014 + bg2.uhce015 AS household__income__100000_to_149999__usd__8,
    bg2.uhce016 AS household__income__150000_to_199999__usd__9,
    bg2.uhce017 AS household__income__200000_or_more__usd__10,
    bg2.ulre001 AS houseunit__total__total_vehicles_available__count__1,
    bg2.ulre003 + bg2.ulre010 AS houseunit__vehicles__none__count__1,
    bg2.ulre004 + bg2.ulre011 AS houseunit__vehicles__one__count__2,
    bg2.ulre005 + bg2.ulre012 AS houseunit__vehicles__two__count__3,
    bg2.ulre006 + bg2.ulre013 AS houseunit__vehicles__three_or_more__count__4,
    bg2.ufce001 AS pop__total__total_pop_commuting_to_work__count__1,
    COALESCE((5 * bg2.ufde002 + 12 * bg2.ufde003 + 17 * bg2.ufde004 + 22 * bg2.ufde005 + 27 * bg2.ufde005 + 32 * bg2.ufde006 + 40 * bg2.ufde007 + 52 * bg2.ufde008 + 60 * bg2.ufde009)::numeric / NULLIF(bg2.ufde001::numeric, 0::numeric), 0::numeric) AS pop__total__commute_mean_travel_time__minutes__1,
    bg2.uffe003 AS pop__commute__drive_alone__count__1,
    bg2.uffe004 AS pop__commute__drive_carpool__count__2,
    bg2.uffe010 AS pop__commute__public_transit__count__3,
    bg2.uffe019 AS pop__commute__walk__count__4,
    bg2.uffe020 AS pop__commute__other_transit__count__5,
    bg2.uffe021 AS pop__commute__work_from_home__count__6,
    ba.housing__building_age__built_2010_or_later__count AS houseunit__building_age__built_2010_or_later__count__1,
    ba.housing__building_age__built_2000_to_2009__count AS houseunit__building_age__built_2000_to_2009__count__2,
    ba.housing__building_age__built_1990_to_1999__count AS houseunit__building_age__built_1990_to_1999__count__3,
    ba.housing__building_age__built_1980_to_1989__count AS houseunit__building_age__built_1980_to_1989__count__4,
    ba.housing__building_age__built_1970_to_1979__count AS houseunit__building_age__built_1970_to_1979__count__5,
    ba.housing__building_age__built_1960_to_1969__count AS houseunit__building_age__built_1960_to_1969__count__6,
    ba.housing__building_age__built_1950_to_1959__count AS houseunit__building_age__built_1950_to_1959__count__7,
    ba.housing__building_age__built_1940_to_1949__count AS houseunit__building_age__built_1940_to_1949__count__8,
    ba.housing__building_age__built_1939_or_earlier__count AS houseunit__building_age__built_1939_or_earlier__count__9,
    gen.pop__generation__generation_z__count AS pop__generation__generation_z__count__1,
    gen.pop__generation__generation_y__count AS pop__generation__generation_y__count__2,
    gen.pop__generation__generation_x__count AS pop__generation__generation_x__count__3,
    gen.pop__generation__baby_boomer__count AS pop__generation__baby_boomer__count__4,
    gen.pop__generation__silent_generation__count AS pop__generation__silent_generation__count__5,
    lang.pop__total__primary_lang_other_than_english__percent AS pop__language__primary_lang_other_than_english__percent__1,
    primlang.pop__total__english_only__count AS pop__language__english_only__count__1,
    primlang.pop__total__spanish__count AS pop__language__spanish__count__2,
    primlang.pop__total__other_indo_european__count AS pop__language__other_indo_european__count__3,
    primlang.pop__total__asian_pacific_islander__count AS pop__language__asian_pacific_islander__count__4,
    primlang.pop__total__other__count AS pop__language__other__count__5,
    enroll.pop__education__enrolled_in_school__count AS pop__education__enrolled_in_school__count__1,
    grad.pop__total__college_graduation_rate__percent AS pop__total__college_graduation_rate__percent__1,
    grad.pop__total__high_school_graduation_rate__percent AS pop__total__high_school_graduation_rate__percent__2,
    under.pop__age__under_20__count AS pop__toal__under_20__count__1,
    pov.house__total__below_poverty_level__count AS household__total__below_poverty_level__count__1,
    pov.house__total__receive_food_stamps__count AS household__total__receive_food_stamps__count__1,
    othervac.house__total__vacancy_rate__percent AS houseunit__total__homeowner_vacancy_rate__percent__1,
    othervac.house__total__vacant_housing_units__count AS houseunit__total__vacant_housing_unit__count__1,
    homevac.house__total__homeowner_vacancy_rate__percent AS houseunit__total__rental_vacancy_rate__percent__1,
    dp_block_group.ugse022 + dp_block_group.ugse023 + dp_block_group.ugse024 + dp_block_group.ugse025 AS pop__total__college_graduate__count__1,
    dp_block_group.ugse017 + dp_block_group.ugse018 + dp_block_group.ugse019 + dp_block_group.ugse020 + dp_block_group.ugse021 + dp_block_group.ugse022 + dp_block_group.ugse023 + dp_block_group.ugse024 + dp_block_group.ugse025 AS pop__total__high_school_graduate__count__1,
    dp_block_group.ugse001 AS pop__total__over_25__count__1,
    bg3.ukye004 AS houseunit__total__vacant_for_sale_only__count__1,
    bg2.ulre002 AS houseunit__owner_vs_renter__owner_occupied__count__1,
    COALESCE(bg2.ulre002::numeric / NULLIF(bg2.ulre001::numeric, 0::numeric), 0::numeric) AS houseunit__owner_vs_renter__owner_occupied__percent__1,
    bg3.ukye002 AS houseunit__total__vacant_for_rent__count__1,
    bg2.ulre009 AS houseunit__owner_vs_renter__renter_occupied__count__2,
    COALESCE(bg2.ulre009::numeric / NULLIF(bg2.ulre001::numeric, 0::numeric), 0::numeric) AS houseunit__owner_vs_renter__renter_occupied__percent__2,
    age.ueee001 - (age.ueee003 + age.ueee027) AS pop__total__over_5__count__1,
    primlang.pop__total__spanish__count + primlang.pop__total__other_indo_european__count + primlang.pop__total__asian_pacific_islander__count + primlang.pop__total__other__count AS pop__total__language_other_than_english__count__1,
    smo.umfe002 + smo.umfe003 AS household__grapi__less_than_15__percent__1,
    smo.umfe004 AS household__grapi__15_to_20__percent__2,
    smo.umfe005 AS household__grapi__20_to_25__percent__3,
    smo.umfe006 AS household__grapi__25_to_30__percent__4,
    smo.umfe007 AS household__grapi__30_to_35__percent__5,
    smo.umfe008 + smo.umfe009 + smo.umfe010 AS household__grapi__35_or_more__percent__6,
    smo.umye003 + smo.umye004 + smo.umye005 AS household__smocapi__less_than_20__percent__1,
    smo.umye006 AS household__smocapi__20_to_25__percent__2,
    smo.umye007 AS household__smocapi__25_to_30__percent__3,
    smo.umye008 AS household__smocapi__30_to_35__percent__4,
    smo.umye009 + smo.umye010 + smo.umye011 AS household__smocapi__35_or_more__percent__5,
    age.ueee020 + age.ueee021 + age.ueee022 + age.ueee023 + age.ueee024 + age.ueee025 + age.ueee044 + age.ueee045 + age.ueee046 + age.ueee047 + age.ueee048 + age.ueee049 AS pop__total__over_65__count__1,
    lai.households AS household__total__total_households__count__1,
    lai.area_median_income AS household__total__area_median_income__usd__1,
    lai.blkgrp_median_income_owners AS household__total__blkgrp_median_income_owners__usd__1,
    lai.blkgrp_median_income_renters AS household__total__blkgrp_median_income_renters__usd__1,
    lai.avg_hh_size_owners AS household__total__avg_hh_size_owners__count__1,
    lai.avg_hh_size_renters AS household__total__avg_hh_size_renters__count__1,
    lai.commuters_per_hh_owners AS household__total__commuters_per_hh_owners__count__1,
    lai.commuters_per_hh_renters AS household__total__commuters_per_hh_renters__count__1,
    lai.pct_renters AS household__total__pct_renters__percent__1,
    lai.gross_hh_density AS household__total__gross_hh_density__count__1,
    lai.median_rooms_per_owner_unit AS household__total__median_rooms_per_owner_unit__count__1,
    lai.median_rooms_per_renter_unit AS household__total__median_rooms_per_renter_unit__count__1,
    lai.pct_detatched_single_family_unit AS household__total__pct_detatched_single_family_unit__percent__1,
    lai.median_commute_distance AS household__total__median_commute_distance__mile__1,
    lai.block_denstiy AS household__total__block_density__count__1,
    lai.employment_access_index AS household__total__employment_access_index__count__1,
    lai.local_job_density AS household__total__local_job_density__count__1,
    lai.local_retail_job_density AS household__total__local_retail_job_density__count__1,
    lai.retail_access_index AS household__total__retail_access_index__count__1,
    
   FROM dp_block_group
     JOIN dp_block_group2 bg2 ON bg2.geoid = dp_block_group.geoid
     JOIN dp_block_group3 bg3 ON bg3.geoid = dp_block_group.geoid
     JOIN upload.building_age ba ON ba.geoid = dp_block_group.geoid
     JOIN upload.generations gen ON gen.geoid = dp_block_group.geoid
     JOIN upload.language_other_than_english lang ON lang.geoid = dp_block_group.geoid
     JOIN upload.primary_language_spoken_at_home primlang ON primlang.geoid = dp_block_group.geoid
     JOIN upload.school_enrollment_public_and_private enroll ON enroll.geoid = dp_block_group.geoid
     JOIN upload.school_graduation_rates grad ON grad.geoid = dp_block_group.geoid
     JOIN bg_poverty_snap pov ON pov.geoid = dp_block_group.geoid
     JOIN bg_other_vacancy othervac ON othervac.geoid = dp_block_group.geoid
     JOIN bg_homeowner_vacancy homevac ON homevac.geoid = dp_block_group.geoid
     JOIN bg_under_20 under ON under.geoid = dp_block_group.geoid
     JOIN upload.bg_sex_by_age age ON age.geoid = dp_block_group.geoid
     JOIN bg_grapi_smocapi smo ON smo.geoid = dp_block_group.geoid
     LEFT JOIN upload.lai_blkgrps lai ON lai.blkgrp = dp_block_group.geoid
     JOIN dash_blockgroup_geo100 block_group_geo ON block_group_geo.blk_grp_id = dp_block_group.geoid::numeric

