alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__total_voters to
voter_reg__affiliation_total_voters__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__democrat to
voter_reg__affiliation_democrat__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__republican to
voter_reg__affiliation_republican__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__none to
voter_reg__affiliation_none__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__other to
voter_reg__affiliation_other__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__unknown to
voter_reg__affiliation_unknown__count;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__percent_dem to
voter_reg__affiliation_percent_dem__percent;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__percent_rep to
voter_reg__affiliation_percent_rep__percent;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__percent_none to
voter_reg__affiliation_percent_none__percent;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__percent_other to
voter_reg__affiliation_percent_other__percent;

alter table affiliation_percentages_blockgroup rename column voter_reg__affiliation__percent_unknown to
voter_reg__affiliation_percent_unknown__percent;
